version: '3.7'

services:
  piggy_api:
    container_name: piggy_api
    build: ./api/
    restart: always
    env_file: .env
    ports:
      - ${NODEJS_PORT}:${NODEJS_PORT}
    volumes:
      - ./api/:/app
      - node_modules:/app/node_modules

volumes:
  node_modules: